services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: sullys
      POSTGRES_PASSWORD: sullys
      POSTGRES_DB: sullys
    ports:
      - "5432:5432"
    volumes:
      - sullys_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  sullys_pg:
